# Generated by Django 3.1.2 on 2020-12-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Shift', models.CharField(max_length=15)),
                ('Dept', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Dob', models.DateField()),
            ],
            options={
                'db_table': 'login_cred',
            },
        ),
    ]
